// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa0RFt793Xr7NJdGTkkWoAwz8JY6iRt3Y',
    appId: '1:339021894682:web:2a566d28828722a524eda3',
    messagingSenderId: '339021894682',
    projectId: 'myrestauranteflutter',
    authDomain: 'myrestauranteflutter.firebaseapp.com',
    storageBucket: 'myrestauranteflutter.firebasestorage.app',
    measurementId: 'G-C71JR84CJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5iyxERkvZaz7Qgs3CyMr-NT9iqjuxx2E',
    appId: '1:339021894682:android:1339bcf1d0394f7324eda3',
    messagingSenderId: '339021894682',
    projectId: 'myrestauranteflutter',
    storageBucket: 'myrestauranteflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJb4rLGN0FNoAHqUqgZorJ_2TI9P_gj0',
    appId: '1:339021894682:ios:622cd9aaac5b7c6d24eda3',
    messagingSenderId: '339021894682',
    projectId: 'myrestauranteflutter',
    storageBucket: 'myrestauranteflutter.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJb4rLGN0FNoAHqUqgZorJ_2TI9P_gj0',
    appId: '1:339021894682:ios:622cd9aaac5b7c6d24eda3',
    messagingSenderId: '339021894682',
    projectId: 'myrestauranteflutter',
    storageBucket: 'myrestauranteflutter.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa0RFt793Xr7NJdGTkkWoAwz8JY6iRt3Y',
    appId: '1:339021894682:web:7928cdaccdd8ca8c24eda3',
    messagingSenderId: '339021894682',
    projectId: 'myrestauranteflutter',
    authDomain: 'myrestauranteflutter.firebaseapp.com',
    storageBucket: 'myrestauranteflutter.firebasestorage.app',
    measurementId: 'G-YQ3ZEK168T',
  );
}
